// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scriptloop-foundation/Board.tsx": () => import("../components/mockups/scriptloop-foundation/Board.tsx"),
  "./components/mockups/scriptloop-immersive/Dashboard.tsx": () => import("../components/mockups/scriptloop-immersive/Dashboard.tsx"),
  "./components/mockups/scriptloop-immersive/ScriptDetail.tsx": () => import("../components/mockups/scriptloop-immersive/ScriptDetail.tsx"),
  "./components/mockups/scriptloop-immersive/ZenMode.tsx": () => import("../components/mockups/scriptloop-immersive/ZenMode.tsx"),
  "./components/mockups/scriptloop-landing/LandingA_Calm.tsx": () => import("../components/mockups/scriptloop-landing/LandingA_Calm.tsx"),
  "./components/mockups/scriptloop-landing/LandingB_Studio.tsx": () => import("../components/mockups/scriptloop-landing/LandingB_Studio.tsx"),
  "./components/mockups/scriptloop-landing/LandingC_Editorial.tsx": () => import("../components/mockups/scriptloop-landing/LandingC_Editorial.tsx"),
  "./components/mockups/scriptloop-minimal/Dashboard.tsx": () => import("../components/mockups/scriptloop-minimal/Dashboard.tsx"),
  "./components/mockups/scriptloop-minimal/ScriptDetail.tsx": () => import("../components/mockups/scriptloop-minimal/ScriptDetail.tsx"),
  "./components/mockups/scriptloop-minimal/ZenMode.tsx": () => import("../components/mockups/scriptloop-minimal/ZenMode.tsx"),
  "./components/mockups/scriptloop-pro/Dashboard.tsx": () => import("../components/mockups/scriptloop-pro/Dashboard.tsx"),
  "./components/mockups/scriptloop-pro/ScriptDetail.tsx": () => import("../components/mockups/scriptloop-pro/ScriptDetail.tsx"),
  "./components/mockups/scriptloop-pro/ZenMode.tsx": () => import("../components/mockups/scriptloop-pro/ZenMode.tsx"),
  "./components/mockups/scriptloop-logos/BrandWorkup.tsx": () => import("../components/mockups/scriptloop-logos/BrandWorkup.tsx"),
  "./components/mockups/scriptloop-logos/KnotS.tsx": () => import("../components/mockups/scriptloop-logos/KnotS.tsx"),
  "./components/mockups/scriptloop-logos/LoopMark.tsx": () => import("../components/mockups/scriptloop-logos/LoopMark.tsx"),
  "./components/mockups/scriptloop-logos/RibbonS.tsx": () => import("../components/mockups/scriptloop-logos/RibbonS.tsx"),
  "./components/mockups/scriptloop-logos/SlimS.tsx": () => import("../components/mockups/scriptloop-logos/SlimS.tsx"),
  "./components/mockups/scriptloop-logos/TiltedS.tsx": () => import("../components/mockups/scriptloop-logos/TiltedS.tsx"),
  "./components/mockups/scriptloop-logos/VerticalMobius.tsx": () => import("../components/mockups/scriptloop-logos/VerticalMobius.tsx")
};
